### PR TITLE
feat: 🎸 Add option to resolve deps using paru (from AUR)

### PR DESCRIPTION
**Pull request by kamack38**
Add option to resolve deps using paru (from AUR)

### CODE REVIEW

**Comment by hapakaien** [comment]
Hey @kamack38, thanks for this PR.

I want to test this in my CI workflow. May I know how I do it? Maybe you can provide an AUR package as an example?

**Comment by kamack38** [comment]
So what about this PR? Do you approve it or do you want some more explanation?

**Comment by hapakaien** [comment]
Yes, I approve this PR. Thanks.

**Comment by kamack38** [comment]
Thanks!

**Pull request merged**
